### ISSUE TITLE
Hosting a "local" registry via git

### ISSUE THREAD

**Issue by psionic-k** [dhovart/cargo-local-registry#196]
I was going to use this to create a fixed set of versions for my team and build servers.  It's super close, but I don't quite see how to adapt the output to host over git and then use as a source.

My strategy, which is almost working, is to list the dependencies that may be used in a centralized dummy crate, generate the lockfile, and then generate the "local" registry from the lockfile.

To use the result in other repos, I seem to need a config.json similar to the [one](https://github.com/rust-lang/crates.io-index/blob/master/config.json) found in https://github.com/rust-lang/crates.io-index

Since the index used by crates.io is in the root, It's not clear if I want to break up the "local" index and crates into two repos or how to properly make a config.json that will work with the local registry format.

The local registry format is so close to just working as a remote registry.  To hack it a bit closer, I made a repo of just the index and then copied the config.json over from crates.io so that crates that were found in the index could download (from crates.io) successfully.  Here was the cargo config:
``` toml
[net]
git-fetch-with-cli = true

[source.crates-io]
registry = 'sparse+https://index.crates.io/'
replace-with = 'positron-registry'

[source.positron-registry]
registry = "ssh://git@positron.repo/registry.git/"
```

And then I just specify all my dependencies like:
``` toml
[dependencies]
thiserror = "*"
```
in repos and they successfully follow the uploaded index to resolve versions.

Since the first part of the problem, preventing version dispersion, was solved by just using the index, I might go with that, but it is tempting to do some extra work and just adopt full vendoring of the crates as well.
